# Generated by Django 5.1.2 on 2024-10-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.disaster')),
            ],
        ),
    ]
